name: complex

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "date = $(date +'%d-%m-%Y')" >> $GITHUB_ENV
    - name: Test the date
      env:
        DATE: ${{ steps.date.outputs.date }}
      run: echo "${{ENV.DATE}}"
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Get date
      id: Date
      run: echo "date = $(date +'%d-%m-%Y')" >> $GITHUB_ENV
    - name: Test what is the date
      run: echo $DATE
      env:
        DATE: ${{ steps.Date.outputs.date }}
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
    - name: Current date
      id: date
      run: echo "date = $(date +'%d-%m-%Y')" >> $GITHUB_ENV
    - name: Test with environment variables
      run: echo $DATE
      env:
        DATE: ${{ steps.date.outputs.date }}
  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [ job1, job2, job3 ]
    steps:
    - name: What's the date?
      id: Calendar
      run: echo "date = $(date +'%d-%m-%Y')" >> $GITHUB_ENV
    - name: Print the date    
      run: echo $DATE
      env:
        DATE: ${{ steps.Calendar.outputs.date }}
      

