name: complex

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
    - name: Test with environment variables
      run: echo $DATE
      env:
        DATE: ${{ steps.date.outputs.date }}
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Get date
      id: Date
      run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
    - name: Test with environment variables
      run: echo $DATE
      env:
        DATE: ${{ steps.Date.outputs.date }}
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
    - name: Current date
      id: DATE
      run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
    - name: Test with environment variables
      run: echo $DATE
      env:
        DATE: ${{ steps.DATE.outputs.date }}


      

