name: complex

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      run: |
        echo "DATE = $(date + '%d-%m-%Y')" >> $GITHUB_ENV
    - name: Print the current date
      run: echo ${{ env.DATE }}



      

