name: complex

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "DATE = $(date + '%d-%m-%Y')" >> $GITHUB_OUTPUT
    - name: Test with environment variables
      run: echo $DATE
      env:
        DATE: $GITHUB_OUTPUT
